export const YANDEX_URL = "https://translate.yandex.net/api/v1.5/tr.json";
export const YANDEX_KEY =
  "trnsl.1.1.20200214T093209Z.770ffb3919b46232.ec06ae1560b2b3f7f06a7ee0cb97b88cc777790f";

interface LanguageInfo {
  language: string;
  languageCode: string;
  countryCode: string;
}

const languagesInfo: LanguageInfo[] = [
  { language: "Afrikaans", languageCode: "af", countryCode: "ZA" },
  { language: "Amharic", languageCode: "am", countryCode: "ET" },
  { language: "Arabic", languageCode: "ar", countryCode: "SA" },
  { language: "Azerbaijani", languageCode: "az", countryCode: "AZ" },
  { language: "Bashkir", languageCode: "ba", countryCode: "RU" },
  { language: "Belarusian", languageCode: "be", countryCode: "BY" },
  { language: "Bulgarian", languageCode: "bg", countryCode: "BG" },
  { language: "Bengali", languageCode: "bn", countryCode: "BD" },
  { language: "Bosnian", languageCode: "bs", countryCode: "BA" },
  { language: "Catalan", languageCode: "ca", countryCode: "ES" },
  { language: "Cebuano", languageCode: "ceb", countryCode: "PH" },
  { language: "Czech", languageCode: "cs", countryCode: "CZ" },
  { language: "Chuvash", languageCode: "cv", countryCode: "RU" },
  { language: "Welsh", languageCode: "cy", countryCode: "GB" },
  { language: "Danish", languageCode: "da", countryCode: "DK" },
  { language: "German", languageCode: "de", countryCode: "DE" },
  { language: "Greek", languageCode: "el", countryCode: "GR" },
  { language: "English", languageCode: "en", countryCode: "GB" },
  { language: "Esperanto", languageCode: "eo", countryCode: "PL" },
  { language: "Spanish", languageCode: "es", countryCode: "ES" },
  { language: "Estonian", languageCode: "et", countryCode: "EE" },
  { language: "Basque", languageCode: "eu", countryCode: "ES" },
  { language: "Persian", languageCode: "fa", countryCode: "IR" },
  { language: "Finnish", languageCode: "fi", countryCode: "FI" },
  { language: "French", languageCode: "fr", countryCode: "FR" },
  { language: "Irish", languageCode: "ga", countryCode: "IE" },
  { language: "Scottish Gaelic", languageCode: "gd", countryCode: "GB" },
  { language: "Galician", languageCode: "gl", countryCode: "ES" },
  { language: "Gujarati", languageCode: "gu", countryCode: "IN" },
  { language: "Hebrew", languageCode: "he", countryCode: "IL" },
  { language: "Hindi", languageCode: "hi", countryCode: "IN" },
  { language: "Croatian", languageCode: "hr", countryCode: "HR" },
  { language: "Haitian", languageCode: "ht", countryCode: "HT" },
  { language: "Hungarian", languageCode: "hu", countryCode: "HU" },
  { language: "Armenian", languageCode: "hy", countryCode: "AM" },
  { language: "Indonesian", languageCode: "id", countryCode: "ID" },
  { language: "Icelandic", languageCode: "is", countryCode: "IS" },
  { language: "Italian", languageCode: "it", countryCode: "IT" },
  { language: "Japanese", languageCode: "ja", countryCode: "JP" },
  { language: "Javanese", languageCode: "jv", countryCode: "ID" },
  { language: "Georgian", languageCode: "ka", countryCode: "GE" },
  { language: "Kazakh", languageCode: "kk", countryCode: "KZ" },
  { language: "Khmer", languageCode: "km", countryCode: "KH" },
  { language: "Kannada", languageCode: "kn", countryCode: "IN" },
  { language: "Korean", languageCode: "ko", countryCode: "KR" },
  { language: "Kyrgyz", languageCode: "ky", countryCode: "KG" },
  { language: "Latin", languageCode: "la", countryCode: "IT" },
  { language: "Luxembourgish", languageCode: "lb", countryCode: "LU" },
  { language: "Lao", languageCode: "lo", countryCode: "LA" },
  { language: "Lithuanian", languageCode: "lt", countryCode: "LT" },
  { language: "Latvian", languageCode: "lv", countryCode: "LV" },
  { language: "Malagasy", languageCode: "mg", countryCode: "MG" },
  { language: "Mari", languageCode: "mhr", countryCode: "RU" },
  { language: "Maori", languageCode: "mi", countryCode: "NZ" },
  { language: "Macedonian", languageCode: "mk", countryCode: "MK" },
  { language: "Malayalam", languageCode: "ml", countryCode: "IN" },
  { language: "Mongolian", languageCode: "mn", countryCode: "MN" },
  { language: "Marathi", languageCode: "mr", countryCode: "IN" },
  { language: "Hill Mari", languageCode: "mrj", countryCode: "RU" },
  { language: "Malay", languageCode: "ms", countryCode: "MY" },
  { language: "Maltese", languageCode: "mt", countryCode: "MT" },
  { language: "Burmese", languageCode: "my", countryCode: "MM" },
  { language: "Nepali", languageCode: "ne", countryCode: "NP" },
  { language: "Dutch", languageCode: "nl", countryCode: "NL" },
  { language: "Norwegian", languageCode: "no", countryCode: "NO" },
  { language: "Punjabi", languageCode: "pa", countryCode: "IN" },
  { language: "Papiamento", languageCode: "pap", countryCode: "AW" },
  { language: "Polish", languageCode: "pl", countryCode: "PL" },
  { language: "Portuguese", languageCode: "pt", countryCode: "PT" },
  { language: "Romanian", languageCode: "ro", countryCode: "RO" },
  { language: "Russian", languageCode: "ru", countryCode: "RU" },
  { language: "Yakut", languageCode: "sah", countryCode: "RU" },
  { language: "Sinhalese", languageCode: "si", countryCode: "LK" },
  { language: "Slovak", languageCode: "sk", countryCode: "SK" },
  { language: "Slovenian", languageCode: "sl", countryCode: "SI" },
  { language: "Albanian", languageCode: "sq", countryCode: "AL" },
  { language: "Serbian", languageCode: "sr", countryCode: "RS" },
  { language: "Sundanese", languageCode: "su", countryCode: "ID" },
  { language: "Swedish", languageCode: "sv", countryCode: "SE" },
  { language: "Swahili", languageCode: "sw", countryCode: "KE" },
  { language: "Tamil", languageCode: "ta", countryCode: "LK" },
  { language: "Telugu", languageCode: "te", countryCode: "IN" },
  { language: "Tajik", languageCode: "tg", countryCode: "TJ" },
  { language: "Thai", languageCode: "th", countryCode: "TH" },
  { language: "Tagalog", languageCode: "tl", countryCode: "PH" },
  { language: "Turkish", languageCode: "tr", countryCode: "TR" },
  { language: "Tatar", languageCode: "tt", countryCode: "RU" },
  { language: "Udmurt", languageCode: "udm", countryCode: "RU" },
  { language: "Ukrainian", languageCode: "uk", countryCode: "UA" },
  { language: "Urdu", languageCode: "ur", countryCode: "PK" },
  { language: "Uzbek", languageCode: "uz", countryCode: "UZ" },
  { language: "Vietnamese", languageCode: "vi", countryCode: "VN" },
  { language: "Xhosa", languageCode: "xh", countryCode: "ZA" },
  { language: "Yiddish", languageCode: "yi", countryCode: "IL" },
  { language: "Chinese", languageCode: "zh", countryCode: "CN" },
];
