export const YANDEX_URL = "https://translate.yandex.net/api/v1.5/tr.json";
export const YANDEX_KEY =
  "trnsl.1.1.20200214T093209Z.770ffb3919b46232.ec06ae1560b2b3f7f06a7ee0cb97b88cc777790f";

interface LanguageInfo {
  language: string;
  languageCode: string;
  countryCode: string;
}

const languagesInfo = [
  { language: "Afrikaans", languageCode: "af", countryCode: "ZA" },
  { language: "Amharic", languageCode: "am", countryCode: "ET" },
  { language: "Arabic", languageCode: "ar", countryCode: "SA" },
  { language: "Azerbaijani", languageCode: "az", countryCode: "AZ" },
  { language: "Bashkir", languageCode: "ba", countryCode: "RU" },
  { language: "Belarusian", languageCode: "be", countryCode: "BY" },
  { language: "Bulgarian", languageCode: "bg", countryCode: "BG" },
  { language: "Bengali", languageCode: "bn", countryCode: "BD" },
  { language: "Bosnian", languageCode: "bs", countryCode: "BA" },
  { language: "Catalan", languageCode: "ca", countryCode: "ES" },
  { language: "Cebuano", languageCode: "ceb", countryCode: "PH" },
  { language: "Czech", languageCode: "cs", countryCode: "CZ" },
  { language: "Chuvash", languageCode: "cv", countryCode: "RU" },
  { language: "Welsh", languageCode: "cy", countryCode: "GB" },
  { language: "Danish", languageCode: "da", countryCode: "DK" },
  { language: "German", languageCode: "de", countryCode: "DE" },
  { language: "Greek", languageCode: "el", countryCode: "GR" },
  { language: "English", languageCode: "en", countryCode: "GB" },
  { language: "Esperanto", languageCode: "eo", countryCode: "PL" },
  { language: "Spanish", languageCode: "es", countryCode: "ES" },
  { language: "Estonian", languageCode: "et", countryCode: "EE" },
  { language: "Basque", languageCode: "eu", countryCode: "ES" },
  { language: "Persian", languageCode: "fa", countryCode: "IR" },
  { language: "Finnish", languageCode: "fi", countryCode: "FI" },
  { language: "French", languageCode: "fr", countryCode: "FR" },
  { language: "Irish", languageCode: "ga", countryCode: "IE" },
  { language: "Scottish Gaelic", languageCode: "gd", countryCode: "GB" },
  { language: "Galician", languageCode: "gl", countryCode: "ES" },
  { language: "Gujarati", languageCode: "gu", countryCode: "IN" },
  { language: "Hebrew", languageCode: "he", countryCode: "IL" },
  { language: "Hindi", languageCode: "hi", countryCode: "IN" },
  { language: "Croatian", languageCode: "hr", countryCode: "HR" },
  { language: "Haitian", languageCode: "ht", countryCode: "HT" },
  { language: "Hungarian", languageCode: "hu", countryCode: "HU" },
  { language: "Armenian", languageCode: "hy", countryCode: "AM" },
  { language: "Indonesian", languageCode: "id", countryCode: "ID" },
  { language: "Icelandic", languageCode: "is", countryCode: "IS" },
  { language: "Italian", languageCode: "it", countryCode: "IT" },
  { language: "Japanese", languageCode: "ja", countryCode: "JP" },
  { language: "Javanese", languageCode: "jv", countryCode: "ID" },
  { language: "Georgian", languageCode: "ka", countryCode: "GE" },
  { language: "Kazakh", languageCode: "kk", countryCode: "KZ" },
  { language: "Khmer", languageCode: "km", countryCode: "KH" },
  { language: "Kannada", languageCode: "kn" },
  { language: "Korean", languageCode: "ko" },
  { language: "Kyrgyz", languageCode: "ky" },
  { language: "Latin", languageCode: "la" },
  { language: "Luxembourgish", languageCode: "lb" },
  { language: "Lao", languageCode: "lo" },
  { language: "Lithuanian", languageCode: "lt" },
  { language: "Latvian", languageCode: "lv" },
  { language: "Malagasy", languageCode: "mg" },
  { language: "Mari", languageCode: "mhr" },
  { language: "Maori", languageCode: "mi" },
  { language: "Macedonian", languageCode: "mk" },
  { language: "Malayalam", languageCode: "ml" },
  { language: "Mongolian", languageCode: "mn" },
  { language: "Marathi", languageCode: "mr" },
  { language: "Hill Mari", languageCode: "mrj" },
  { language: "Malay", languageCode: "ms" },
  { language: "Maltese", languageCode: "mt" },
  { language: "Burmese", languageCode: "my" },
  { language: "Nepali", languageCode: "ne" },
  { language: "Dutch", languageCode: "nl" },
  { language: "Norwegian", languageCode: "no" },
  { language: "Punjabi", languageCode: "pa" },
  { language: "Papiamento", languageCode: "pap" },
  { language: "Polish", languageCode: "pl" },
  { language: "Portuguese", languageCode: "pt" },
  { language: "Romanian", languageCode: "ro" },
  { language: "Russian", languageCode: "ru" },
  { language: "Yakut", languageCode: "sah" },
  { language: "Sinhalese", languageCode: "si" },
  { language: "Slovak", languageCode: "sk" },
  { language: "Slovenian", languageCode: "sl" },
  { language: "Albanian", languageCode: "sq" },
  { language: "Serbian", languageCode: "sr" },
  { language: "Sundanese", languageCode: "su" },
  { language: "Swedish", languageCode: "sv" },
  { language: "Swahili", languageCode: "sw" },
  { language: "Tamil", languageCode: "ta" },
  { language: "Telugu", languageCode: "te" },
  { language: "Tajik", languageCode: "tg" },
  { language: "Thai", languageCode: "th" },
  { language: "Tagalog", languageCode: "tl" },
  { language: "Turkish", languageCode: "tr" },
  { language: "Tatar", languageCode: "tt" },
  { language: "Udmurt", languageCode: "udm" },
  { language: "Ukrainian", languageCode: "uk" },
  { language: "Urdu", languageCode: "ur" },
  { language: "Uzbek", languageCode: "uz" },
  { language: "Vietnamese", languageCode: "vi" },
  { language: "Xhosa", languageCode: "xh" },
  { language: "Yiddish", languageCode: "yi" },
  { language: "Chinese", languageCode: "zh" },
];
